---
  - name: Check if docker-compose file exists
    ansible.builtin.stat:
      path: "{{ HOME_ASSISTANT_PATH }}/docs/docker-compose.yml"
    register: home_assistant_stat_docker_compose_file

  - name: Docker Compose Start Apps
    community.docker.docker_compose:
      project_src: "{{ HOME_ASSISTANT_PATH }}/docs"
      files: "docker-compose.yml"
      state: present
      pull: true
    when: home_assistant_stat_docker_compose_file.stat.exists

